In [1]:
import torch

In [ ]:
x = torch.Tensor([1, 2, 4])
x

tensor([1., 2., 4.])

In [3]:
print(x)

tensor([1., 2., 4.])


In [5]:
y = torch.Tensor([
    [3, 4],
    [902, 9]
])
y

tensor([[  3.,   4.],
        [902.,   9.]])

In [10]:
z = torch.zeros((2, 3))
z

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [11]:
o = torch.ones((3, 2))
o

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [13]:
r = torch.rand((3, 2))
r

tensor([[0.9723, 0.3431],
        [0.9543, 0.1687],
        [0.4131, 0.3805]])

In [14]:
r.shape

torch.Size([3, 2])

In [16]:
r[2][1]

tensor(0.3805)

In [17]:
r[2, 1]

tensor(0.3805)

In [20]:
z@o

tensor([[0., 0.],
        [0., 0.]])

In [22]:
8+z

tensor([[8., 8., 8.],
        [8., 8., 8.]])

In [23]:
4*o

tensor([[4., 4.],
        [4., 4.],
        [4., 4.]])

In [24]:
import numpy as np

In [25]:
arr = np.array([10, 20, 30])

In [26]:
n = torch.from_numpy(arr) # Pytorch is taking memory address not copy the elements

In [27]:
n

tensor([10, 20, 30])

In [28]:
arr

array([10, 20, 30])

Linear regression

In [32]:
X = torch.randn(100, 1)
y = 2 * X + 1 + 0.1 * torch.randn(100, 1)

In [35]:
x

tensor([1, 2, 3, 4])

In [34]:
y

tensor([[-2.5164],
        [ 3.1096],
        [ 0.6506],
        [ 4.0149],
        [ 5.4705],
        [ 2.5321],
        [ 2.1609],
        [ 2.2285],
        [ 0.4858],
        [-0.7283],
        [-3.0931],
        [ 1.0929],
        [-3.5087],
        [ 3.5908],
        [ 3.3331],
        [ 2.3191],
        [ 0.2034],
        [-0.2176],
        [ 1.0240],
        [-0.8820],
        [ 2.2846],
        [ 0.0740],
        [ 5.2068],
        [ 2.8495],
        [ 1.6207],
        [ 4.3668],
        [ 2.3481],
        [-1.6157],
        [-0.0428],
        [-2.4200],
        [ 1.1384],
        [ 0.7852],
        [ 1.6064],
        [ 0.3668],
        [ 1.8604],
        [-0.1181],
        [ 0.3700],
        [-1.5114],
        [ 1.4281],
        [ 4.2299],
        [-1.5359],
        [-0.8793],
        [ 1.5688],
        [ 1.1229],
        [ 3.0299],
        [ 1.2777],
        [-2.4336],
        [-2.9893],
        [ 2.8568],
        [-0.5510],
        [ 1.4338],
        [ 1.4950],
        [ 0.

In [36]:
w = torch.randn(1, 1, requires_grad=True)
b = torch.randn(1, requires_grad=True)

In [37]:
w

tensor([[-0.0745]], requires_grad=True)

In [38]:
b

tensor([1.2708], requires_grad=True)

In [39]:
learning_rate = 0.1
epochs = 100

In [40]:
for epoch in range(epochs):
    # Forward pass (Element-wise multiplication + broadcasting)
    y_pred = X * w + b
    
    # Compute Mean Squared Error (MSE) Loss
    loss = ((y_pred - y) ** 2).mean()
    
    # Backward pass (Compute gradients)
    loss.backward()
    
    # Update weights using gradient descent (no_grad prevents tracking these updates)
    with torch.no_grad():
        w -= learning_rate * w.grad
        b -= learning_rate * b.grad
        
        # Zero out the gradients for the next epoch
        w.grad.zero_()
        b.grad.zero_()

In [41]:

print(f"Trained weight (w): {w.item():.4f}, bias (b): {b.item():.4f}")
print(f"Final Loss: {loss.item():.4f}")

Trained weight (w): 1.9875, bias (b): 1.0168
Final Loss: 0.0130
