In [4]:
from tensorflow.keras.preprocessing.text import one_hot

In [6]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
## Define the vocabulary size
voc_size=10000

In [11]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size) for words in sent]
one_hot_repr

[[9130, 1502, 6913, 8186],
 [9130, 1502, 6913, 6240],
 [9130, 9395, 6913, 1777],
 [9535, 4561, 275, 973, 9400],
 [9535, 4561, 275, 973, 4058],
 [620, 9130, 7261, 6913, 2394],
 [3455, 3344, 4619, 973]]

In [3]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [12]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 9130 1502 6913 8186]
 [   0    0    0    0 9130 1502 6913 6240]
 [   0    0    0    0 9130 9395 6913 1777]
 [   0    0    0 9535 4561  275  973 9400]
 [   0    0    0 9535 4561  275  973 4058]
 [   0    0    0  620 9130 7261 6913 2394]
 [   0    0    0    0 3455 3344 4619  973]]


In [13]:
## feature representation
dim=10

In [14]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

c:\Users\aksha\Documents\github\ML_learning\.venv\Lib\site-packages\keras\src\layers\core\embedding.py:103: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [15]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [16]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 242ms/step


array([[[ 0.03086319,  0.02686799, -0.02860924, -0.01283487,
         -0.02958686,  0.00216048, -0.00835568,  0.01713686,
          0.03944517,  0.02553834],
        [ 0.03086319,  0.02686799, -0.02860924, -0.01283487,
         -0.02958686,  0.00216048, -0.00835568,  0.01713686,
          0.03944517,  0.02553834],
        [ 0.03086319,  0.02686799, -0.02860924, -0.01283487,
         -0.02958686,  0.00216048, -0.00835568,  0.01713686,
          0.03944517,  0.02553834],
        [ 0.03086319,  0.02686799, -0.02860924, -0.01283487,
         -0.02958686,  0.00216048, -0.00835568,  0.01713686,
          0.03944517,  0.02553834],
        [-0.00494908, -0.02986646,  0.04743094, -0.01757883,
         -0.00961152, -0.00106511,  0.00945852,  0.03068242,
         -0.01396372, -0.0388626 ],
        [ 0.03849408, -0.00107618, -0.04302132,  0.02745701,
          0.02768531, -0.01387   ,  0.02965887, -0.02030189,
          0.00667175, -0.00651895],
        [-0.04663304,  0.04454703,  0.00345016,  0.0

In [18]:
embedded_docs[0]

array([   0,    0,    0,    0, 9130, 1502, 6913, 8186], dtype=int32)

In [19]:
model.predict(embedded_docs[[0]])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step


array([[[ 0.03086319,  0.02686799, -0.02860924, -0.01283487,
         -0.02958686,  0.00216048, -0.00835568,  0.01713686,
          0.03944517,  0.02553834],
        [ 0.03086319,  0.02686799, -0.02860924, -0.01283487,
         -0.02958686,  0.00216048, -0.00835568,  0.01713686,
          0.03944517,  0.02553834],
        [ 0.03086319,  0.02686799, -0.02860924, -0.01283487,
         -0.02958686,  0.00216048, -0.00835568,  0.01713686,
          0.03944517,  0.02553834],
        [ 0.03086319,  0.02686799, -0.02860924, -0.01283487,
         -0.02958686,  0.00216048, -0.00835568,  0.01713686,
          0.03944517,  0.02553834],
        [-0.00494908, -0.02986646,  0.04743094, -0.01757883,
         -0.00961152, -0.00106511,  0.00945852,  0.03068242,
         -0.01396372, -0.0388626 ],
        [ 0.03849408, -0.00107618, -0.04302132,  0.02745701,
          0.02768531, -0.01387   ,  0.02965887, -0.02030189,
          0.00667175, -0.00651895],
        [-0.04663304,  0.04454703,  0.00345016,  0.0